### ISSUE TITLE
Add suport for source maps

### ISSUE THREAD

**Issue by ottonascarella** [mraaroncruz/guard-uglify#1]
Hi there,

First off, thanks for building this.

Secondly: Can we have a way to minify files with source map, since it's supported by Uglify nowadays?

**Comment by mraaroncruz** [comment]
I will do my best to make some time for this.
This library should be updated anyway and adding source map support looks fairly trivial.
It's nice to know at least one person is using this library :P

**Comment by ottonascarella** [comment]
Dude...this library is THE BOMB! 8¬)

It's been used in a tutorial by NETTUTS....so it should be pretty "well
used" around the globe.
http://net.tutsplus.com/tutorials/tools-and-tips/guard-is-your-best-friend/

On 26 June 2013 08:31, Aaron Cruz notifications@github.com wrote:

> I will do my best to make some time for this.
> This library should be updated anyway and adding source map support looks
> fairly trivial.
> It's nice to know at least one person is using this library :P
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pferdefleisch/guard-uglify/issues/1#issuecomment-20040892
> .

## 

Otto
